### ISSUE TITLE
Error while creating a vault secret

### ISSUE THREAD

**Issue by adityavarmak** [crossplane-contrib/provider-azure#346]
### What happened?

While creating a keyvault secret i am getting the below error.
. Status=401 Code="Unauthorized" Message="AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.azure.com/.

### How can we reproduce it?

The code I am using
```apiVersion: keyvault.azure.crossplane.io/v1alpha1
kind: KeyVaultSecret
metadata:
  name: example2255
spec:
  forProvider:
    vaultBaseUrl: 'https://myvault.vault.azure.net/'
    name: test-secret
    attributes:
      enabled: true
      notBeforeDate: '2022-12-30T00:00:00Z'
      expirationDate: '2022-12-30T00:00:00Z'
    value:
      namespace: crossplane-system
      name: example-azure-keyvault-secret
      key: value
    contentType: text/plain
    tags:
      created_by: crossplane
  providerConfigRef:
    name: provider-azure 
```

### What environment did it happen in?
Crossplane version:  v0.19.0

**Comment by jgpelaez** [comment]
We have same problem creating vault, as temporary solution we added a new providerconfig:

```
apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  labels:
    argocd.argoproj.io/instance: crossplane-providers-hxops-dev-euw-aks
  name: provider-azure-vault
spec:
  credentials:
    secretRef:
      key: credentials-vault.json
      name: azure-provider-credentials
      namespace: crossplane-system
    source: Secret
```

In credentials-vault.json, there is small change in the json, with 

```
"resourceManagerEndpointUrl": "https://vault.azure.net/",
```

Works.

Anyway we also think that this is a bug on the provider
