### ISSUE TITLE
APIDiagnostic resource shall allow empty string as acceptable value

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/provider-azure#387]
### What happened?

Have following spec for APIDiagnostics
```
apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: APIDiagnostic
metadata:
  name: local
spec:
  providerConfigRef:
    name: workload-identity-provider-config
  forProvider:
    apiManagementLoggerId: ""
    alwaysLogErrors: true
    apiManagementNameRef:
      name: apim-service-reference
    resourceGroupNameRef:
      name: rg-reference
    apiNameRef:
      name: open-api
    httpCorrelationProtocol: W3C
    logClientIp: true
    samplingPercentage: 100
    verbosity: verbose
```

### How can we reproduce it?

Try to deploy resource with spec above and resource would fail to create with error  ` Message:               cannot patch the managed resource via server-side apply: APIDiagnostic.apimanagement.azure.upbound.io "local" is invalid: spec.forProvider.apiManagementLoggerId: Invalid value: "null": spec.forProvider.apiManagementLoggerId in body must be of type string: "null"` 
Empty string value is proper entry for `local` debugging in Azure API Management

![Image](https://github.com/user-attachments/assets/f61cab3d-f6d0-4787-ae13-17aa42a0fbcc)

![Image](https://github.com/user-attachments/assets/9a56a823-1f9c-44ba-9c97-b1c2546d8ea7)

### What environment did it happen in?
Crossplane version: 1.11.1
